### ISSUE TITLE
Errors have ramped up recently

### ISSUE THREAD

**Issue by geokscott** [sergeymaysak/wirelesstagpy#10]
Sergey, is this something new going on with the wrapper?

My HA is getting a lot of these everyday:

failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2:26:48 PM – (ERROR) /usr/local/lib/python3.9/site-packages/wirelesstagpy/__init__.py - message first occurred at 2:15:53 PM and shows up 8 times
failed to fetch push update: syntax error: line 1, column 0
2:26:47 PM – (ERROR) /usr/local/lib/python3.9/site-packages/wirelesstagpy/__init__.py - message first occurred at 2:16:01 PM and shows up 3 times

**Comment by sergeymaysak** [comment]
@geokscott - no changes from my side. You are not alone in reporting this. I cannot reproduce it  - do you face issue now?

**Comment by geokscott** [comment]
It's extremely intermittent. But yesterday was the worst, I didn't get updates for 6 hours.

**Comment by geokscott** [comment]
error log from today

```
2021-10-04 13:06:46 ERROR (Thread-4) [wirelesstagpy] failed to fetch push update: syntax error: line 1, column 0
2021-10-04 13:06:46 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:46 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:47 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:47 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:48 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:48 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:48 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:48 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:49 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:49 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:49 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:49 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:50 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:50 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:50 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:50 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:51 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:51 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:51 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:51 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:52 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:52 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:52 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:57 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:57 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:57 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:57 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:06:58 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:07:04 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:07:05 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:07:09 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:07:09 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:07:09 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:07:10 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 13:07:13 ERROR (Thread-4) [wirelesstagpy] failed to fetch push update: syntax error: line 1, column 0
2021-10-04 13:07:14 ERROR (Thread-4) [wirelesstagpy] failed to fetch push update: syntax error: line 1, column 0
2021-10-04 16:46:21 ERROR (Thread-4) [wirelesstagpy] failed to fetch push update: syntax error: line 1, column 0
2021-10-04 16:46:21 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 16:46:21 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 16:46:22 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 16:46:22 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 16:46:22 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 16:53:18 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-10-04 21:21:25 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 21:21:25 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 21:21:33 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 21:21:33 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 21:21:41 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 21:21:42 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 21:21:42 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 21:21:42 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 21:21:42 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
2021-10-04 21:21:43 ERROR (Thread-4) [wirelesstagpy] failed to get cloud push: Unable to login to wirelesstags.net - check your credentials
```
